-- MySQL Script generated by MySQL Workbench
-- Wed Jan 27 09:33:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `clanky-krizik`.`kategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clanky-krizik`.`kategorie` (
  `idkategorie` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idkategorie`),
  UNIQUE INDEX `idkategorie_UNIQUE` (`idkategorie` ASC),
  UNIQUE INDEX `nazev_UNIQUE` (`nazev` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clanky-krizik`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clanky-krizik`.`autor` (
  `idautor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(255) NOT NULL,
  `prijmeni` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idautor`),
  UNIQUE INDEX `idautor_UNIQUE` (`idautor` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clanky-krizik`.`clanky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clanky-krizik`.`clanky` (
  `idclanky` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulek` VARCHAR(255) NOT NULL,
  `obsah` TEXT NOT NULL,
  `idkategorie` INT UNSIGNED NOT NULL,
  `idautor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idclanky`, `idkategorie`, `idautor`),
  UNIQUE INDEX `idclanky_UNIQUE` (`idclanky` ASC),
  UNIQUE INDEX `titulek_UNIQUE` (`titulek` ASC),
  INDEX `fk_clanky_kategorie_idx` (`idkategorie` ASC),
  INDEX `fk_clanky_autor1_idx` (`idautor` ASC),
  CONSTRAINT `fk_clanky_kategorie`
    FOREIGN KEY (`idkategorie`)
    REFERENCES `clanky-krizik`.`kategorie` (`idkategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clanky_autor1`
    FOREIGN KEY (`idautor`)
    REFERENCES `clanky-krizik`.`autor` (`idautor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
